In [1]:
import numpy as np

arr = np.arange(24)

arr_3d = arr.reshape(4, 3, 2)

final_arr = arr_3d.transpose(0, 2, 1)

print("Final shape:", final_arr.shape)
print(final_arr)


Final shape: (4, 2, 3)
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]
