In [1]:
import numpy as np

scores = np.random.randint(50, 101, size=(5, 3))

mean_scores = scores.mean(axis=0)

centered_scores = scores - mean_scores

print("Original Scores:\n", scores)
print("\nCentered Scores:\n", centered_scores)


Original Scores:
 [[ 75  56 100]
 [ 67  57  77]
 [ 61  54  64]
 [ 55  87  71]
 [100  97  75]]

Centered Scores:
 [[  3.4 -14.2  22.6]
 [ -4.6 -13.2  -0.4]
 [-10.6 -16.2 -13.4]
 [-16.6  16.8  -6.4]
 [ 28.4  26.8  -2.4]]
